version: '3.8'

services:
  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    build:
      context: "./image-templates"
      dockerfile: ${UBUNTU_DOCKERFILE}
    image: ubuntu1
    privileged: true
    volumes:
      - ./data/ubuntu1/home/guest:/home/guest
      - ./data/ubuntu1/root:/root
    ports:
      - ${UBUNTU1_PORT_SSHD}:22
      - ${UBUNTU1_PORT_TTYD}:7681
    networks:
      - container_net

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    build:
      context: "./image-templates"
      dockerfile: ${UBUNTU_DOCKERFILE}
    image: ubuntu2
    privileged: true
    volumes:
      - ./data/ubuntu2/home/guest:/home/guest
      - ./data/ubuntu2/root:/root
    ports:
      - ${UBUNTU2_PORT_SSHD}:22
      - ${UBUNTU2_PORT_TTYD}:7681
    networks:
      - container_net

  fedora1:
    hostname: fedora1
    container_name: fedora1
    build:
      context: "./image-templates"
      dockerfile: ${FEDORA_DOCKERFILE}
    image: fedora1
    privileged: true
    volumes:
      - ./data/fedora1/home/guest:/home/guest
      - ./data/fedora1/root:/root
    ports:
      - ${FEDORA1_PORT_SSHD}:22
      - ${FEDORA1_PORT_TTYD}:7681
    networks:
      - container_net

  fedora2:
    hostname: fedora2
    container_name: fedora2
    build:
      context: "./image-templates"
      dockerfile: ${FEDORA_DOCKERFILE}
    image: fedora2
    privileged: true
    volumes:
      - ./data/fedora2/home/guest:/home/guest
      - ./data/fedora2/root:/root
    ports:
      - ${FEDORA2_PORT_SSHD}:22
      - ${FEDORA2_PORT_TTYD}:7681
    networks:
      - container_net

networks:
  container_net:
    name: container_net